from utils import click_element, scrool_bar , ss_alma
from selenium.webdriver.common.by import By  
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import datetime
import time
def call_page(driver):
    try:
        driver.find_element(By.XPATH , '//*[@id="app"]/div/nav/nav/div/div/div[1]/div[2]/div/div/div[1]').click()
        time.sleep(2)
        print("1")
        driver.find_element(By.XPATH , '//*[@id="app"]/div/nav/nav/div/div/div[1]/div[2]/div/div/div[2]/a[1]').click()
        time.sleep(2)
        print("2")
        search_bar = driver.find_element(By.XPATH , '//*[@id="search"]')
        search_bar.click()
        search_bar.send_keys("emir")
        search_bar.send_keys(Keys.ENTER)
        print("3")
        #dropdown menü
        time.sleep(2)
        driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[2]/div/div[2]/div/div[2]').click()
        driver.find_element(By.XPATH , '//*[@id="status-0"]/span').click()
        print("4")
        date = driver.find_element(By.XPATH , '//*[@id="date"]')
        date.click()
        date.send_keys("01/01/2021")

        time.sleep(2)
        print("5")
        driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[2]/div/div[4]/button').click()
        time.sleep(2)

        name = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[2]/div/form/div[1]/input')
        name.click()
        today_date = datetime.datetime.now().strftime("%d/%m/%Y")
        name.send_keys(f"emir {today_date}")
        time.sleep(1)
        print("6")
        driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[2]/div/form/div[2]/div/div[2]').click()
        time.sleep(2)
        driver.find_element(By.XPATH , '//*[@id="null-0"]').click()
        time.sleep(2)
        print("7")
        #flowup mesajları
        driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[2]/div/form/div[3]/div/div/div[2]').click()
        time.sleep(2)
        # "sms" seçeneğini seç
        sms_option = driver.find_element(By.XPATH, "//span[contains(text(), 'sms')]")
        sms_option.click()
        time.sleep(2)
        print("8")
        return_call = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[2]/div/form/div[4]/div[2]/div/input')
        return_call.click()
        return_call.send_keys("1")

        driver.find_element(By.XPATH , '//*[@id="default-checkbox"]').click()
        time.sleep(2)
        print("9")
        call_frequency = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[2]/div/form/div[5]/div/input')
        call_frequency.click()
        call_frequency.send_keys("1")   
        print("10")
        description = driver.find_element(By.XPATH , '//*[@id="notes"]')
        description.click()
        description.send_keys("Kullanıcının bir ford marka arabası vardır 2021 model en son bakımlarını 3 mart günü yapmıştır.")

        driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[2]/div/form/div[7]/button[2]').click()
        print("11 call")
        time.sleep(5)
        click_element(driver,By.CLASS_NAME,"swal2-styled","call_page_ok_button")
        print("11.1 ")
        time.sleep(5)
        # konuşmaya tıkla
        div_element = driver.find_element(By.XPATH, '//*[@id="app"]/div/main/div/div[3]/div/table/tbody/tr[1]/td[1]')
        div_element.click()
        print("12 call")
        time.sleep(4)
        #follow up mesajıdır.
        followup_button = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[4]/div[2]/button[1]')
        followup_button.click()
        time.sleep(2)
        message_add = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[4]/div/div[2]/div/div/div/button[2]')
        message_add.click()
        time.sleep(2)
        print("13")
        status_add = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[4]/div/div[2]/div/table/tbody/tr/td[1]/div/div[2]')
        status_add.click()
        time.sleep(2)
        status_add_element = driver.find_element(By.XPATH , '//*[@id="null-2"]')
        status_add_element.click()  
        time.sleep(2)
        print("14")
        message_text = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[4]/div/div[2]/div/table/tbody/tr/td[2]/form/input')
        message_text.send_keys("Bu bir follow-up mesajıdır")  
        time.sleep(2)
        driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[4]/div/div[2]/div/table/tbody/tr/td[3]/button[1]').click()
        time.sleep(2)
        print("14.1")
        driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[4]/div/div[3]/div[1]/div/button').click()
        time.sleep(2)
        print("15")
        status_add = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[4]/div/div[2]/div/table/tbody/tr/td[1]/div/div[2]')
        status_add.click()
        time.sleep(2)
        status_add_element = driver.find_element(By.XPATH , '//*[@id="null-4"]/span')
        status_add_element.click()  
        print("16")
        message_text2 = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[4]/div/div[2]/div/table/tbody/tr[2]/td[2]/form/input')
        message_text2.send_keys("Bu bir follow-up mesajıdır")    
        time.sleep(2)
        driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[4]/div/div[2]/div/table/tbody/tr[2]/td[3]/button[2]').click()
        print("17 CALL")
        driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[4]/div/div[2]/div/table/tbody/tr/td[3]/button[2]').click()
        time.sleep(2)
        WebDriverWait(driver, 8).until(EC.element_to_be_clickable((By.CLASS_NAME, "swal2-confirm"))).click()
        time.sleep(2)
        print("18")
        yapay_zeka_oluştur = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[4]/div/div[2]/div/div/div/button[1]')
        yapay_zeka_oluştur.click()
        time.sleep(2)
        time.sleep(50)
        print("19")
        close_followup = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[4]/div/div[3]/div[2]/button[2]')
        close_followup.click()
        time.sleep(2)
        #sohbet mesajı oluştur
        chat_add = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[4]/div[2]/button[2]')
        chat_add.click()
        time.sleep(3)
        print("20")
        yapay_zeka_button = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[3]/div/div/div[2]/div/div/div/button[1]')
        yapay_zeka_button.click()
        time.sleep(2)
        konu_message = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[3]/div[1]/div/form/div[1]/textarea')
        konu_message.send_keys("Müşterimize abonelik yenileme teklifinde bulunacağız. Geçmiş faturalar ve kullanım analizleri doğrultusunda kişiye özel kampanyalar sunarak ikna etmeye çalışacağız.")
        print("21")
        time.sleep(2)
        driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[3]/div[1]/div/form/div[2]/button[2]').click()
        time.sleep(15)
        print("22")
        WebDriverWait(driver, 8).until(EC.element_to_be_clickable((By.CLASS_NAME, "swal2-confirm"))).click()
        time.sleep(2)
        scrool_bar(driver)
        time.sleep(2)
        print("23 call")
        chat_follow_close = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[3]/div/div/div[1]/button')
        chat_follow_close.click()
        time.sleep(2)

        #customer add

        customer_add = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[4]/button[2]')
        customer_add.click()
        time.sleep(2)
        print("24")
        customer_select = driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[3]/div/form/div[1]/div/div[1]')
        print("24.1")
        customer_select.click()
        print("24.2.1")
        text_enter = driver.find_element(By.XPATH , '//*[@id="null-0"]')
        text_enter.click()
        print("24.2")
        time.sleep(2)
        customer_info = driver.find_element(By.XPATH , '//*[@id="note"]')
        time.sleep(2)
        print("24.4")
        customer_info.send_keys("Müşterimizin abonelik süresi dolmak üzere. Müşterimizle iletişime geçerek abonelik süresini uzatmaya çalışacağız. ")
        time.sleep(2)
        print("24.5")
        driver.find_element(By.XPATH , '//*[@id="app"]/div/main/div/div[3]/div/form/div[3]/button[2]').click()
        print("25")
        time.sleep(2)
        WebDriverWait(driver, 8).until(EC.element_to_be_clickable((By.CLASS_NAME, "swal2-confirm"))).click()

        print("Giden Arama Sayfası Görüntülendi")
        ss_alma("ss/callpage_basarili.png")
        time.sleep(2)
    except Exception as e:
        print(f"Call page fonksiyonunda hata oluştu : {e}")
        ss_alma("ss/callpage_error.png")

