import time
from selenium.webdriver.common.by import By  
from utils import click_element , close_popup , ss_alma


def settings_pages(driver):
    try:
        print("Settings testi başladı")
        driver.find_element(By.XPATH,'//*[@id="app"]/div/nav/nav/div/div/div[1]/div[2]/div/a[3]').click()
        time.sleep(5)  
        # Company Name
        companyName = driver.find_element(By.XPATH, '//*[@id="companyName"]')
        companyName.clear()
        time.sleep(1)
        companyName.send_keys("Emirhan İpek Test 1")
        time.sleep(1)
        click_submit = driver.find_element(By.XPATH, '//*[@id="app"]/div/main/div/form/div[5]/button')
        click_submit.click()
        close_popup(driver)
        time.sleep(2)
        
        print("Company Name başarıyla güncellendi")
        # Short Name
        shortname = driver.find_element(By.XPATH, '//*[@id="shortName"]')
        shortname.clear()
        time.sleep(1)
        shortname.send_keys("Eİ TEST")
        time.sleep(1)
        click_submit = driver.find_element(By.XPATH, '//*[@id="app"]/div/main/div/form/div[5]/button')
        click_submit.click()
        time.sleep(2)
        close_popup(driver)
        print("Short Name başarıyla güncellendi")
        # Phone
        phone = driver.find_element(By.XPATH, '//*[@id="phone"]')
        phone.clear()
        time.sleep(1)
        phone.send_keys('+905413609917')
        time.sleep(1)
        click_submit = driver.find_element(By.XPATH, '//*[@id="app"]/div/main/div/form/div[5]/button')
        click_submit.click()
        time.sleep(2)
        close_popup(driver)
        print("Phone başarıyla güncellendi")
        # Email
        email = driver.find_element(By.XPATH, '//*[@id="email"]')
        email.clear()
        time.sleep(1)
        email.send_keys('emirhan.ipek@siriusaitech.com')
        time.sleep(1)
        click_submit = driver.find_element(By.XPATH, '//*[@id="app"]/div/main/div/form/div[5]/button')
        click_submit.click()
        time.sleep(2)
        close_popup(driver)
        print("Email başarıyla güncellendi")
        # Address
        address = driver.find_element(By.XPATH, '//*[@id="address"]')
        address.clear()
        time.sleep(1)
        address.send_keys("İSTANBUL ESENYURT")
        time.sleep(1)
        click_submit = driver.find_element(By.XPATH, '//*[@id="app"]/div/main/div/form/div[5]/button')
        click_submit.click()
        time.sleep(2)
        close_popup(driver)
        print("Address başarıyla güncellendi")
        # Start Time
        startsAt = driver.find_element(By.XPATH, '//*[@id="startsAt"]')
        startsAt.clear()
        time.sleep(1)
        startsAt.send_keys("09:00")
        time.sleep(1)
        click_submit = driver.find_element(By.XPATH, '//*[@id="app"]/div/main/div/form/div[5]/button')
        click_submit.click()
        time.sleep(2)
        close_popup(driver)
        print("Start Time başarıyla güncellendi")
        # Finish Time
        finishesAt = driver.find_element(By.XPATH, '//*[@id="finishesAt"]')
        finishesAt.clear()
        time.sleep(1)
        finishesAt.send_keys("17:00")
        time.sleep(1)
        click_submit = driver.find_element(By.XPATH, '//*[@id="app"]/div/main/div/form/div[5]/button')
        click_submit.click()
        time.sleep(2)
        close_popup(driver)
        print("Finish Time başarıyla güncellendi")
        # About Us
        aboutus = driver.find_element(By.XPATH, '//*[@id="about"]')
        aboutus.clear()
        time.sleep(1)
        aboutus.send_keys("""7/24 Transfer olarak, VIP taşımacılık hizmetlerimizle tüm Türkiye genelinde güvenli, konforlu ve zamanında ulaşım sağlıyoruz. Havalimanlarından başlayarak geniş transfer ağımız sayesinde müşterilerimize en iyi hizmeti sunmayı hedefliyoruz.
        Çalışma saatlerimiz hafta içi 09:00 - 17:30 arasındadır. Geniş araç filomuz ile her türlü transfer ihtiyacınıza cevap verecek kapasitedeyiz. Profesyonel ekibimiz ve deneyimli şoförlerimiz ile müşteri memnuniyetini ön planda tutuyor, her yolculuğunuzda kaliteli bir deneyim sunuyoruz.""")
        time.sleep(1)
        click_submit = driver.find_element(By.XPATH, '//*[@id="app"]/div/main/div/form/div[5]/button')
        click_submit.click()
        time.sleep(2)
        close_popup(driver)
        print("About Us başarıyla güncellendi")
        # Assistant Name
        assistantName = driver.find_element(By.XPATH, '//*[@id="assistantName"]')
        assistantName.clear()
        time.sleep(1)
        assistantName.send_keys("7/24 Asistan")
        time.sleep(1)
        click_submit = driver.find_element(By.XPATH, '//*[@id="app"]/div/main/div/form/div[5]/button')
        click_submit.click()
        time.sleep(2)
        close_popup(driver)
        time.sleep(2)
        ss_alma("ss/settings_page.png")

        print("Settings test başarıyla tamamlandı")
        
    except Exception as e:
        print(f"Bir hata oluştu: {e}")